// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Lab3test4Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void lab3test4() {
    driver.Navigate().GoToUrl("http://20.50.171.10:8080/");
    driver.Manage().Window.Size = new System.Drawing.Size(1232, 683);
    driver.FindElement(By.CssSelector(".ownerTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) > a")).Click();
    driver.FindElement(By.LinkText("Lab3Test1 test")).Click();
    driver.FindElement(By.CssSelector(".editOwner")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(2)")).Click();
    driver.FindElement(By.Id("firstName")).SendKeys("  ");
    driver.FindElement(By.CssSelector(".form-group:nth-child(3)")).Click();
    driver.FindElement(By.Id("lastName")).SendKeys("  ");
    driver.FindElement(By.CssSelector(".form-group:nth-child(4)")).Click();
    driver.FindElement(By.Id("address")).SendKeys("  ");
    driver.FindElement(By.CssSelector("app-owner-edit > .container-fluid")).Click();
    driver.FindElement(By.CssSelector(".updateOwner")).Click();
  }
}
